name: Pull Request - Application

on:
  pull_request:
    branches: 
      - main

jobs:
  application:
    uses: codbex/codbex-infra/.github/workflows/application-pull-request.yaml@main
    with:
      application-name: codbex-hestia
      install-dependencies: true
    secrets: inherit
  application-data-sample:
    uses: codbex/codbex-infra/.github/workflows/application-build.yaml@main
    with:
      application-name: codbex-hestia-data-sample
      install-dependencies: true
      dockerfile-location: application-data-sample/
    secrets: inherit
